### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by sebastianpc** [AtjonTV/AltAccountAutoBan#1]
Soo just by decompiling in luyten or any other editor you will be able to get mysql info

**Comment by AtjonTV** [comment]
2 Thing, First the MySQL-Server is dead, Second the User Data was only for this 'Application'.

I am going to remake the Plugin with a new 'Database' .. in the new version i won't be using MySQL, instead i am downloading a .json file that servs as a local database and only gets downloaded if a new version is avaibale.

(After one week the MySQL-Server was overloaded because of the limitation of 20 Connections and about 30 Server running my Plugin xD)

I am getting in development of the new Plugin, right now! Github: https://github.com/AtjonTV/AAAB/tree/dev-1.0 

[If you want, you can help .. if you have a question or want to talk: admin.atjontv@atvg-studios.at ]
